### ISSUE TITLE
Pipes are broken on consecutive points along an axis

### ISSUE THREAD

**Issue by strich** [federicocasares/unity-plumber#1]
This code has been working fantastically, however I ran into a trivial edge case that breaks the pipe:
![image](https://user-images.githubusercontent.com/987896/68802898-ba410980-0656-11ea-8c6b-15753a82876f.png)
![image](https://user-images.githubusercontent.com/987896/68802913-c331db00-0656-11ea-84e0-69561e7798e1.png)

I'm afraid I wasn't able to work my way around the math easily. I wonder if it is a case missing in the conversion to the left hand coords?

**Comment by federicocasares** [comment]
Hello, and thank you for your report! Does it happen in every single axis or only when keepping X and Y constant?

**Comment by strich** [comment]
I think only when keeping them constant. You can see a few other hints when you play with it too:

- If you make point3.X = 15.1 it'll resolve correctly. Makes me feeling like maybe the direction calculation isn't taking into account if a segment direction isn't left or right but instead straight?
- Changing the elbow segments doesn't fix the pictured issue, but if you make it big enough (Try 1.5) it'll create even more issues.

**Comment by federicocasares** [comment]
But do you experience the same problem with any set of colinear points? Or only if they are aligned with the Z axis? For example, do these sets also cause problems?

- (0,0,0), (1,0,0), (2,0,0)
- (0,0,0), (0,1,0), (0,2,0)
- (0,0,0), (1,1,0), (2,2,0)

**Comment by strich** [comment]
Ah. Yep same issue:
![image](https://user-images.githubusercontent.com/987896/68871511-74d31980-06f4-11ea-80e4-846c9d4f5bb3.png)
![image](https://user-images.githubusercontent.com/987896/68871701-c085c300-06f4-11ea-9e84-a2989395a705.png)

**Comment by federicocasares** [comment]
I have just pushed a fix that automatically removes colinear points from the list to prevent this issue from happening. Basically we ended up with an edge case that tries to create an elbow with infinite radius when points are colinear, so it's better to avoid them altogether. Thanks for your report!
